[versions]
kotlin = "2.0.0"

[libraries.kotlin-gradle]
version.ref = "kotlin"
module = "org.jetbrains.kotlin:kotlin-gradle-plugin"

[libraries.dokka]
version = "1.9.10"
module = "org.jetbrains.dokka:dokka-gradle-plugin"

[libraries.kotlinx-binary-compatibility]
version = "0.13.2"
module = "org.jetbrains.kotlinx:binary-compatibility-validator"
