package inkapplications.spondee.structure

data class SiScale(val factor: Double, val symbol: String)

val Yotta = SiScale(1e24, "Y")
val Zetta = SiScale(1e21, "Z")
val Exa = SiScale(1e18, "E")
val Peta = SiScale(1e15, "P")
val Tera = SiScale(1e12, "T")
val Giga = SiScale(1e9, "G")
val Mega = SiScale(1e6, "M")
val Kilo = SiScale(1e3, "k")
val Hecto = SiScale(1e2, "h")
val Deka = SiScale(1e1, "da")
val Deci = SiScale(1e-1, "d")
val Centi = SiScale(1e-2, "c")
val Milli = SiScale(1e-3, "m")
val Micro = SiScale(1e-6, "mu")
val Nano = SiScale(1e-9, "n")
val Pico = SiScale(1e-12, "p")
val Femto = SiScale(1e-15, "f")
val Atto = SiScale(1e-18, "a")
val Zepto = SiScale(1e-21, "z")
val Yocto = SiScale(1e-24, "y")
